### ISSUE TITLE
BUG: Clicking ability in game causes fatal scar error

### ISSUE THREAD

**Issue by RagnarTheEverchosen** [JustCodiex/coh2-battlegrounds#115]
SCAR ERROR Callstack: 
   C               [C]                            Ln   -1 (LOC)
  Lua             api_ui.scar"]                  Ln  193 (BGUI_ShowWarning)
  Lua             shared_abilities.scar"]        Ln   34 (BGAE_OnModalPhase)
21:33:20.64   GameObj::OnFatalScarError: [Invalid parameter 1 (type expected=const char*, received=nil) in function LOC
  Lua             api_ui.scar"]                  Ln  193 (BGUI_ShowWarning)
  Lua             shared_abilities.scar"]        Ln   34 (BGAE_OnModalPhase)

**Comment by JustCodiex** [comment]
This will be solved by #119
