### ISSUE TITLE
TODO: WPF lib

### ISSUE THREAD

**Issue by RagnarTheEverchosen** [JustCodiex/coh2-battlegrounds#212]
make a wpf library to make code better testable

**Comment by JustCodiex** [comment]
Moving down in the pipeline, since this will make WPF/Server testing easier in the future

**Comment by JustCodiex** [comment]
Mainly done... (Still some quirks, like those god-awful dropdowns).

Will also implement a redefined method for reading icons etc. to make it easier to add stuff and less required to compile the entire project when updating.

**Comment by JustCodiex** [comment]
Closing this
